### ISSUE TITLE
Accelerator / Shortcut / Hotkey

### ISSUE THREAD

**Issue by ElectricPrism** [rastersoft/panther_launcher#1]
Hello :) I was wondering if Panther Launcher has a shortcut / accel to launch it as most Application Menus do.

Something like: Alt + F1 / Super / Super + Space / Super + A etc..

If it doesn't, I highly recommend this feature and that I could edit the accel from org.rastersoft.panther toggle-visability-accel []

**Comment by rastersoft** [comment]
Hi. Currently it hasn't it, but it is a good idea. Give me some time.

**Comment by rastersoft** [comment]
Done. Now you can use Super + Q (because Super + A is already taken for "show all icons). Also, ESC key closes the launcher if it is open.

I'm building the packages.

**Comment by rastersoft** [comment]
Packages built and available in my home page

**Comment by ElectricPrism** [comment]
Thank you, I've been using the .tar.xz provided for pacman from the homepage with success. Excellent work :)
