### ISSUE TITLE
not compiling on fedora 24

### ISSUE THREAD

**Issue by tarmtrollet** [rastersoft/panther_launcher#10]
Hi!

nice work with the launcher!

im getting an error when compiling on fedora 24:

  Can't find any of the files /usr/lib/pkgconfig/libpanel-applet.pc
  /usr/lib64/pkgconfig/libpanel-applet.pc

am i missing a dependency?

and the precomplied package at http://www.rastersoft.com/programas/panther_launcher.html cant be activated in gnome-tweak-tool the version im getting when im downloading from your  site is "panther_launcher.fedora24-1.10.1-2.x86_64.rpm" and it says that 1.11.0-r2 is needed for fedora 24 in the changelog.

thanks :)

**Comment by rastersoft** [comment]
Hi:

Yes, you need the development packages for gnome-flashback installed in your system.

About the version in my homepage, tell me: which gnome shell version are you using?

**Comment by rastersoft** [comment]
Anyway, check the file /usr/share/gnome-shell/extensions/slingshotgnome@rastersoft.com/metadata.json (after installing the rpm package), and check the gnome shell versions supported. Maybe there is the problem...

**Comment by rastersoft** [comment]
I'm preparing a new batch of packages. Should fix this... Give me a couple of minutes...

**Comment by rastersoft** [comment]
Ok, try the new package (1.11.2).

**Comment by tarmtrollet** [comment]
Hi!

where can i find 1.11.2 the links here http://www.rastersoft.com/programas/panther_launcher.html gives me 1.10.1-2 and that version cant be enabled in tweak-tools, my gnome version is "GNOME Shell 3.20.4"

/usr/share/gnome-shell/extensions/slingshotgnome@rastersoft.com/metadata.json says that 3.20 should be supported.

thanks.

**Comment by tarmtrollet** [comment]
i installed version 1.11.2-1 from your homepage, unfortunately it have the same issue, it cant be activated from tweak-tool

**Comment by tarmtrollet** [comment]
im getting these errors when installing
`warning: Schema 'org.freedesktop.Telepathy.Logger' has path '/apps/telepathy-logger/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.freedesktop.gstreamer-0.10.default-elements' has path '/desktop/gstreamer/0.10/default-elements/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.freedesktop.ibus' has path '/desktop/ibus/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.freedesktop.ibus.general' has path '/desktop/ibus/general/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.freedesktop.ibus.general.hotkey' has path '/desktop/ibus/general/hotkey/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.freedesktop.ibus.panel' has path '/desktop/ibus/panel/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.crypto.cache' has path '/desktop/gnome/crypto/cache/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.crypto.pgp' has path '/desktop/gnome/crypto/pgp/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.seahorse' has path '/apps/seahorse/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.seahorse.manager' has path '/apps/seahorse/listing/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.seahorse.recipients' has path '/apps/seahorse/recipients/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.locale' has path '/system/locale/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy' has path '/system/proxy/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.http' has path '/system/proxy/http/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.https' has path '/system/proxy/https/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.ftp' has path '/system/proxy/ftp/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.socks' has path '/system/proxy/socks/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
`

**Comment by rastersoft** [comment]
Those errors should not prevent panther launcher to work...

Try to launch it from a command line (open a terminal and type "panther_launcher"). If it works, the problem is exclusively in the gnome shell extension.

Also, check that you don't have an old version of the extension at /usr/local/share/gnome-shell/extensions, neither at ~/.local/share/gnome-shell/extensions/ (delete any "slingshotgnome@rastersoft.com" folder inside them).

**Comment by tarmtrollet** [comment]
Hi,

there are no other versions installed, launching from terminal is not working either. the errors i get when launching in terminal are:
`*\* (panther_launcher:3350): WARNING **: App.vala:188: Could not load icon. Falling back to method 2

*\* (panther_launcher:3350): WARNING **: App.vala:221: Could not load icon. Falling back to method 4

*\* (panther_launcher:3350): WARNING **: App.vala:229: Could not load icon. Falling back to method 5

*\* (panther_launcher:3350): ERROR **: App.vala:237: Could not find a fallback icon to load
fish: 'panther_launcher' terminated by signal SIGTRAP`

thank you for helping :)

**Comment by rastersoft** [comment]
WOW! A Sigtrap... that is really odd...

Try to install gnome-panel-devel and gnome-panel-libs from https://copr.fedorainfracloud.org/coprs/yselkowitz/gnome-flashback/ , try to compile it from the sources, and tell me if it works.

I have to do some changes in autovala to allow to do conditional compilation for this...

**Comment by tarmtrollet** [comment]
tried to compile again, now i got an error about missing CMakeLists.txt in panther_launcher-master/src/Widgets and panther_launcher-master/src/Backend

CMake Error at CMakeLists.txt:67 (add_subdirectory):
  The source directory

```
/home/emil/install/panther_launcher-master/src/Widgets
```

  does not contain a CMakeLists.txt file."

and

CMake Error at CMakeLists.txt:59 (add_subdirectory):
  The source directory

```
/home/emil/install/panther_launcher-master/src/Backend
```

  does not contain a CMakeLists.txt file.

**Comment by tarmtrollet** [comment]
we can close this now :) i installed gnome-icon-theme-legacy and after that the precompiled package started working

## Thanks for your help!

**Comment by rastersoft** [comment]
Ok, I take note for adding that package in the dependencies list. Also added those both CMakeLists.txt files, that where missing from the git repository.

Thanks!!!

**Comment by rastersoft** [comment]
Ok, I ended the changes in both Autovala and Panther_launcher to allow to choose whether to compile or not the gnome-panel applet.
