### ISSUE TITLE
cmake is unable to find packages

### ISSUE THREAD

**Issue by rahulv3a** [rastersoft/panther_launcher#2]
I'm using Fedora 22 which has Gnome 3.16. Cmake is unable to find packages even though I have them installed. When run `cmake ..`, I get the following error:

```
-- checking for modules 'atk;cairo;gdk-3.0;gdk-pixbuf-2.0;gee-0.8;gio-2.0;gio-unix-2.0;glib-2.0;gobject-2.0;gtk+-3.0;json-glib-1.0;libgnome-menu-3.0;libsoup-2.4;pango;pangocairo;x11'
--   package 'atk' not found
--   package 'cairo' not found
--   package 'gdk-3.0' not found
--   package 'gdk-pixbuf-2.0' not found
--   package 'gee-0.8' not found
--   package 'gio-2.0' not found
--   package 'gio-unix-2.0' not found
--   package 'glib-2.0' not found
--   package 'gobject-2.0' not found
--   package 'gtk+-3.0' not found
--   package 'json-glib-1.0' not found
--   package 'libgnome-menu-3.0' not found
--   package 'libsoup-2.4' not found
--   package 'pango' not found
--   package 'pangocairo' not found
--   package 'x11' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  CMakeLists.txt:50 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
```

**Comment by rastersoft** [comment]
Be sure that you installed the **devel** packages, which are different than the regular ones. Example: the package _libsoup_ contains the library libsoup-2.4, but you need to also install _libsoup-devel_, which contains the headers and other files needed for compiling.

**Comment by rastersoft** [comment]
Also remember that you have precompiled packages at my homepage: http://www.rastersoft.com

**Comment by rahulv3a** [comment]
I didn't know about the precompiled ones.  I have just tried the one for Fedora x64 and it worked like a charm! Thank you!

PS: I think you should mention precompiled packages in README.md :)
