### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by sudo-give-me-coffee** [rastersoft/panther_launcher#21]
Even if packages has been installed i get the following error message:

-- Checking for modules 'atk;cairo;gdk-3.0;gdk-pixbuf-2.0;gee-0.8;gio-2.0;gio-unix-2.0;glib-2.0;gobject-2.0;gtk+-3.0;json-glib-1.0;libgnome-menu-3.0;libsoup-2.4;pango;pangocairo;x11'
--   No package 'json-glib-1.0' found
--   No package 'libgnome-menu-3.0' found
--   No package 'libsoup-2.4' found

Suggestion:

Add possibility to set position X and Y from command line

**Comment by rastersoft** [comment]
You must install the development packages. In Debian and derivatives they end in "-dev", and in Fedora and derivatives they end in "-devel".
