### ISSUE TITLE
Migrate to gitlab

### ISSUE THREAD

**Issue by ElectricPrism** [rastersoft/panther_launcher#25]
Hi, I follow your work.

I am deleting and depreciating a lot of my github content and suggesting others do the same now that Microsoft has bought GitHub.

I suggest moving to https://gitlab.org for hosting, https://gitlab.gnome.org or self-hosting.

If you do make the move let us know via README.me what the new URL is, thanks :) :+1:

**Comment by rastersoft** [comment]
Hi:

I understand your concerns: for someone like me, who's over the 40's and lived "in first person" the worst parts of the Microsoft vs. Linux battle (including the infamous halloween documents, and even literally being caught in the middle when advocating against the standardization process of OOXML), having them "controlling" my projects in any way is disturbing.

Having said that, I don't think that you should do this kind of campaign this way. Honestly, it is quite violent receiving a personal message like that, telling me what I should do as I were a child. I already read all about this, and, in fact, I am already preparing to migrate my repositories into gitlab, but at this moment I have a peak in my job-that-pays-the-bills, so I can't do it at least until the weekend.

I am pretty sure that your reasons are honest, but I don't think that going through all the repositories posting a message to the proprietaries advocating them to migrate is a good idea. If I'm creating libre software I already know what it means and probably I keep myself informed about these things. If I care about that and already decided to migrate, your message is useless; but if I "don't give a damn" about using a service hosted by microsoft, or just think that maybe they have changed, or whatever..., and I decided not to migrate, your message is quite insulting.

If your intention is only to ensure that you know where to find the code, I think you should rewrite your message as something like:

"Hi, I follow your work. After the recent events, with Microsoft acquiring Github, a lot of people are moving their repositories to https://gitlab.org or https://gitlab.gnome.org. If you decide to move, can you please add a note in the README.md to allow people to find the new code?".

Or something like that.

No offense.

**Comment by ElectricPrism** [comment]
Thank you for communicating your perspective, I am sorry that my message came across the way it did. I didn't mean to step on your toes and I think very highly of you and the work you contribute to the community.

My suggestion is simply a result of me being very concerned about the potential damage the Microsoft GitHub merger could mean for our open community as they have historically fought and tried to annihilate open source projects like OpenGL and Linux.

Again I appologize and wish you well on your private and public works. No worries, and always looking foreward to see what you got cooking, Take care.
