### ISSUE TITLE
Ubuntu .deb showing errors

### ISSUE THREAD

**Issue by AjinkyaDahale** [rastersoft/panther_launcher#4]
Dunno if this is the right place to post this, but this warning shows up if I try to install the DEB available on http://www.rastersoft.com/programas/panther_launcher.html:
Lintian check results for /home/ajinkya/Downloads/panther-launcher-vivid_1.3.0-ubuntu1_amd64.deb:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LANG = "en_IN.ISO8859-1"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
E: panther-launcher: control-file-has-bad-owner postinst 1000/1000 != root/root
E: panther-launcher: control-file-has-bad-owner postrm 1000/1000 != root/root
E: panther-launcher: control-interpreter-without-depends control/rules #!/usr/bin/make

**Comment by rastersoft** [comment]
I uploaded new packages. Try them and tell me if this is fixed, please.

**Comment by AjinkyaDahale** [comment]
It doesn't seem so. Since the error remains the same after you uploaded new packages, there might be some problem in my own PC. Will check and tell. Thanks for the quick response.

**Comment by rastersoft** [comment]
It is probable: I installed those packages in my system and they worked fine :?
