### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by mboisvertdupras** [rastersoft/panther_launcher#5]
Using the latest build for Fedora provided on your website (1.3.0-2), it seems the View as Grid and View as Categories icons are missing.

Running Fedora 23 with GNOME Shell 3.18
![image](http://i.imgur.com/iYOmn1I.png)

**Comment by rastersoft** [comment]
Hi:

Try this, run in a shell this command:

  gtk-update-icon-cache -f -t /usr/share/icons/hicolor
  killall panther_launcher

try again and tell me if it works or not, to know what to do.

Thanks.

**Comment by rastersoft** [comment]
BTW: are you using the rpm package, or you are compiling the source code?

**Comment by rastersoft** [comment]
I installed a Fedora 23 in VirtualBox and everything worked like a charm... :?

**Comment by mboisvertdupras** [comment]
After a reboot the icons appeared, not sure what went wrong. For reference I installed from the rpm package.
