### ISSUE TITLE
icon tiles

### ISSUE THREAD

**Issue by aval984** [rastersoft/panther_launcher#6]
first off panther is awesome it is exactly the kind of launcher i was looking for. the only issue i am having is the size of the tiles the icons sit on. is there some way to change their size? I'm running antergos and I've used dconf to change the icon size, however the tiles don't change. maybe im just a noob and cant find it. thanks for any help
-andrew

**Comment by rastersoft** [comment]
Good point. I'll work on it this weekend.

**Comment by rastersoft** [comment]
Ok, it should work now. Please, update your repository, compile panther launcher again, test it, and tell me if it works fine to launch the oficial version.

And don't forget to kill panther launcher before trying this new version ;)

**Comment by aval984** [comment]
yes the tile now scales with the icon size to a point, the text limits the size. however now im having a problem editing the amount of rows and columns, in dconf editor anyways. ill change the values and hit apply but it resets when i launch panther again, even if i set the use default button it resets.

**Comment by rastersoft** [comment]
Yes, I changed it to use always about 4/9 of the screen's width, and up to 2/5 of the height.

**Comment by rastersoft** [comment]
Ok, I changed it again. Now, if "rows" is zero, will calculate the optimal value, but if it is another number, will use that as the number of rows. The same for the columns.

**Comment by aval984** [comment]
cool. works awesome. the only issue is the text under the icons. if the icons are too small the text will overlap the other tiles. not that big of a problem unless you like small icons. i keep mine around 50 so its not a issue. the text for transmission hits the edge of the tile around 46 not sure about any of the built in apps, i use a custom .menu file with a custom category to only display the apps i want.

**Comment by rastersoft** [comment]
In that case, you need to change the system font to make it smaller. Anyway, I'll check if it is possible to change the size.

**Comment by rastersoft** [comment]
Ok, now you can also change the font size. Please, test it and tell me if all works fine.

**Comment by aval984** [comment]
wow this is awesome. looks great. i love the level of precision you can get the font size to. the only way this could possibly get any better is if the font size scaled with the tile. i wish i knew more about programming to work out things like this, but thanks for your hard work in fixing my issues.
-Andrew

**Comment by rastersoft** [comment]
I considered it, but then I realized what would happen:

User1: Hey, when I put icon size to XX, the font is too small. Can you fix it?

I fix it

User2: Hey, when I put icon size to YY, the font is too big. Can you fix it?

I fix it

User1: Hey, now when I put icon size to ZZ, the font is too big, but before it worked like a charm. Can you fix it?

And so on, and so on 😅 So it is better to have two controls, and allow everyone to put both to exactly what they want.
